### ISSUE TITLE
Making the bottom app bar play nicer with Android Q gestures

### ISSUE THREAD

**Issue by refi64** [jamiesanson/Mammut#12]
Android Q's new gestures make the upwards swipe go to home, and the system gesture area is inset into the app's area. Mammut's bottom bar is *mostly* fine, but it's easy to accidentally go home when I meant to open the menu.

One way of solving this could maybe be a bit of padding inside or under the bottom bar. I noticed the padding on the fab is a bit uneven (presumably to make the fab a bit higher):

![](https://i.ibb.co/QdNhgTg/Screenshot-20190512-184857.png)

so maybe the bottom bar could be grown a bit into this space?

**Comment by jamiesanson** [comment]
It's on my list of things to do before the next release 😎 The plan is to do something similar to the Google I/O app when filters were applied to the schedule, which is simply increase the peek height of the bottom nav/sheet to be the regular peek height + bottom exclusion zone height

**Comment by jamiesanson** [comment]
Edge-to-edge drawing added in 0.6
