### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Marukesu** [jamiesanson/Mammut#13]
Similar to #2, but when I click in authorize, it redirect to a web error page saying "ERR_UNKNOWN_URL_SCHEME"

**Comment by Marukesu** [comment]
Update, it's seems to happen only when I use the Android webview instead of chrome webview

**Comment by Dehelssey** [comment]
Hello there, same problem here : i end up on a page with "ERR_UNKNOWN_URL_SCHEME" when trying to log in but i don't know how to tell my phone / your app to use chrome webview and not android webview like it seemed to work for @MrMarukesu =/

**Comment by jamiesanson** [comment]
Oh jeez, it sounds like I might not have tested it with the Android webview then. I'll look in to this before the next release. Thanks for the report!

**Comment by jamiesanson** [comment]
Fixed in 25f7fa74138aefc8ba80b1e4fe0354950eca6188
