### ISSUE TITLE
compile issue(s)

### ISSUE THREAD

**Issue by dennis-sheil** [jamiesanson/Mammut#3]
There are compile issues around instance secrets.  The app/build.gradle points to keys.gradle, which does not exist.  Then gradle can not find INSTANCES_SECRET.  Then the app won't build because InstancesRepository.kt is looking for BuildConfig.INSTANCES_SECRET as well.  This should probably be explained by a comment in app/build.gradle, or in the README, or dealt with otherwise.

**Comment by jamiesanson** [comment]
Hey there,

Yes I agree, this should be explained somewhere. I'm looking at putting more work into code health and documentation for this repository near the end of the week. I'll address this then. For now, grab yourself some API credentials from https://instances.social/ and create a file named `keys.gradle` with this line:

```
ext.INSTANCES_SECRET = "\"your_secret_here\""
```
